// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/analysis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalysisService_StartAnalysis_FullMethodName     = "/analysis.AnalysisService/StartAnalysis"
	AnalysisService_StreamProgress_FullMethodName    = "/analysis.AnalysisService/StreamProgress"
	AnalysisService_GetResult_FullMethodName         = "/analysis.AnalysisService/GetResult"
	AnalysisService_CancelAnalysis_FullMethodName    = "/analysis.AnalysisService/CancelAnalysis"
	AnalysisService_LoginWithGoogle_FullMethodName   = "/analysis.AnalysisService/LoginWithGoogle"
	AnalysisService_GetUserProfile_FullMethodName    = "/analysis.AnalysisService/GetUserProfile"
	AnalysisService_GetUserHistory_FullMethodName    = "/analysis.AnalysisService/GetUserHistory"
	AnalysisService_GetUploadURL_FullMethodName      = "/analysis.AnalysisService/GetUploadURL"
	AnalysisService_GetAnalysisResult_FullMethodName = "/analysis.AnalysisService/GetAnalysisResult"
)

// AnalysisServiceClient is the client API for AnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 서비스 정의
type AnalysisServiceClient interface {
	// 분석 시작
	StartAnalysis(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error)
	// 실시간 진행 상황 스트리밍
	StreamProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error)
	// 결과 조회
	GetResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*AnalysisResult, error)
	// 작업 취소 (선택 사항)
	CancelAnalysis(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// Auth & User 기능을 위한 RPC 추가 ---
	LoginWithGoogle(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetUserProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
	GetUserHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
	// S3 Presigned URL 발급 ---
	GetUploadURL(ctx context.Context, in *UploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error)
	// 분석 결과 조회 (video_id 기반) ---
	GetAnalysisResult(ctx context.Context, in *AnalysisResultRequest, opts ...grpc.CallOption) (*AnalysisResultResponse, error)
}

type analysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalysisServiceClient(cc grpc.ClientConnInterface) AnalysisServiceClient {
	return &analysisServiceClient{cc}
}

func (c *analysisServiceClient) StartAnalysis(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResponse)
	err := c.cc.Invoke(ctx, AnalysisService_StartAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) StreamProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnalysisService_ServiceDesc.Streams[0], AnalysisService_StreamProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProgressRequest, ProgressEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_StreamProgressClient = grpc.ServerStreamingClient[ProgressEvent]

func (c *analysisServiceClient) GetResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*AnalysisResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResult)
	err := c.cc.Invoke(ctx, AnalysisService_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) CancelAnalysis(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, AnalysisService_CancelAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) LoginWithGoogle(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AnalysisService_LoginWithGoogle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) GetUserProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) GetUserHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetUserHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) GetUploadURL(ctx context.Context, in *UploadURLRequest, opts ...grpc.CallOption) (*UploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadURLResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analysisServiceClient) GetAnalysisResult(ctx context.Context, in *AnalysisResultRequest, opts ...grpc.CallOption) (*AnalysisResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResultResponse)
	err := c.cc.Invoke(ctx, AnalysisService_GetAnalysisResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalysisServiceServer is the server API for AnalysisService service.
// All implementations must embed UnimplementedAnalysisServiceServer
// for forward compatibility.
//
// 서비스 정의
type AnalysisServiceServer interface {
	// 분석 시작
	StartAnalysis(context.Context, *AnalysisRequest) (*AnalysisResponse, error)
	// 실시간 진행 상황 스트리밍
	StreamProgress(*ProgressRequest, grpc.ServerStreamingServer[ProgressEvent]) error
	// 결과 조회
	GetResult(context.Context, *ResultRequest) (*AnalysisResult, error)
	// 작업 취소 (선택 사항)
	CancelAnalysis(context.Context, *CancelRequest) (*CancelResponse, error)
	// Auth & User 기능을 위한 RPC 추가 ---
	LoginWithGoogle(context.Context, *LoginRequest) (*LoginResponse, error)
	GetUserProfile(context.Context, *GetProfileRequest) (*UserProfileResponse, error)
	GetUserHistory(context.Context, *GetHistoryRequest) (*HistoryResponse, error)
	// S3 Presigned URL 발급 ---
	GetUploadURL(context.Context, *UploadURLRequest) (*UploadURLResponse, error)
	// 분석 결과 조회 (video_id 기반) ---
	GetAnalysisResult(context.Context, *AnalysisResultRequest) (*AnalysisResultResponse, error)
	mustEmbedUnimplementedAnalysisServiceServer()
}

// UnimplementedAnalysisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalysisServiceServer struct{}

func (UnimplementedAnalysisServiceServer) StartAnalysis(context.Context, *AnalysisRequest) (*AnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAnalysis not implemented")
}
func (UnimplementedAnalysisServiceServer) StreamProgress(*ProgressRequest, grpc.ServerStreamingServer[ProgressEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedAnalysisServiceServer) GetResult(context.Context, *ResultRequest) (*AnalysisResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedAnalysisServiceServer) CancelAnalysis(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAnalysis not implemented")
}
func (UnimplementedAnalysisServiceServer) LoginWithGoogle(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginWithGoogle not implemented")
}
func (UnimplementedAnalysisServiceServer) GetUserProfile(context.Context, *GetProfileRequest) (*UserProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedAnalysisServiceServer) GetUserHistory(context.Context, *GetHistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserHistory not implemented")
}
func (UnimplementedAnalysisServiceServer) GetUploadURL(context.Context, *UploadURLRequest) (*UploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadURL not implemented")
}
func (UnimplementedAnalysisServiceServer) GetAnalysisResult(context.Context, *AnalysisResultRequest) (*AnalysisResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalysisResult not implemented")
}
func (UnimplementedAnalysisServiceServer) mustEmbedUnimplementedAnalysisServiceServer() {}
func (UnimplementedAnalysisServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalysisServiceServer will
// result in compilation errors.
type UnsafeAnalysisServiceServer interface {
	mustEmbedUnimplementedAnalysisServiceServer()
}

func RegisterAnalysisServiceServer(s grpc.ServiceRegistrar, srv AnalysisServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalysisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalysisService_ServiceDesc, srv)
}

func _AnalysisService_StartAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).StartAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_StartAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).StartAnalysis(ctx, req.(*AnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnalysisServiceServer).StreamProgress(m, &grpc.GenericServerStream[ProgressRequest, ProgressEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnalysisService_StreamProgressServer = grpc.ServerStreamingServer[ProgressEvent]

func _AnalysisService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetResult(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_CancelAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).CancelAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_CancelAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).CancelAnalysis(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_LoginWithGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).LoginWithGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_LoginWithGoogle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).LoginWithGoogle(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetUserProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_GetUserHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetUserHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetUserHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetUserHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_GetUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetUploadURL(ctx, req.(*UploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalysisService_GetAnalysisResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalysisServiceServer).GetAnalysisResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalysisService_GetAnalysisResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalysisServiceServer).GetAnalysisResult(ctx, req.(*AnalysisResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalysisService_ServiceDesc is the grpc.ServiceDesc for AnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analysis.AnalysisService",
	HandlerType: (*AnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAnalysis",
			Handler:    _AnalysisService_StartAnalysis_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _AnalysisService_GetResult_Handler,
		},
		{
			MethodName: "CancelAnalysis",
			Handler:    _AnalysisService_CancelAnalysis_Handler,
		},
		{
			MethodName: "LoginWithGoogle",
			Handler:    _AnalysisService_LoginWithGoogle_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _AnalysisService_GetUserProfile_Handler,
		},
		{
			MethodName: "GetUserHistory",
			Handler:    _AnalysisService_GetUserHistory_Handler,
		},
		{
			MethodName: "GetUploadURL",
			Handler:    _AnalysisService_GetUploadURL_Handler,
		},
		{
			MethodName: "GetAnalysisResult",
			Handler:    _AnalysisService_GetAnalysisResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProgress",
			Handler:       _AnalysisService_StreamProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/analysis.proto",
}
