// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Options       *AnalysisOptions       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_proto_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *AnalysisRequest) GetOptions() *AnalysisOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type AnalysisOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Sensitivity      int32                  `protobuf:"varint,1,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"` // 0=Low, 1=Medium, 2=High
	AnalyzeComments  bool                   `protobuf:"varint,2,opt,name=analyze_comments,json=analyzeComments,proto3" json:"analyze_comments,omitempty"`
	TopCommentsCount int32                  `protobuf:"varint,3,opt,name=top_comments_count,json=topCommentsCount,proto3" json:"top_comments_count,omitempty"` // 기본 10
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalysisOptions) Reset() {
	*x = AnalysisOptions{}
	mi := &file_proto_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisOptions) ProtoMessage() {}

func (x *AnalysisOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisOptions.ProtoReflect.Descriptor instead.
func (*AnalysisOptions) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisOptions) GetSensitivity() int32 {
	if x != nil {
		return x.Sensitivity
	}
	return 0
}

func (x *AnalysisOptions) GetAnalyzeComments() bool {
	if x != nil {
		return x.AnalyzeComments
	}
	return false
}

func (x *AnalysisOptions) GetTopCommentsCount() int32 {
	if x != nil {
		return x.TopCommentsCount
	}
	return 0
}

type AnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_proto_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_proto_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *ProgressRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ProgressEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "log", "progress", "complete", "error"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Progress      int32                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"` // 0-100
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressEvent) Reset() {
	*x = ProgressEvent{}
	mi := &file_proto_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressEvent) ProtoMessage() {}

func (x *ProgressEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressEvent.ProtoReflect.Descriptor instead.
func (*ProgressEvent) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProgressEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressEvent) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_proto_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *ResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type AnalysisResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	VideoId        string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Metadata       *VideoMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SafetyScore    int32                  `protobuf:"varint,4,opt,name=safety_score,json=safetyScore,proto3" json:"safety_score,omitempty"`
	Categories     []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	GeminiResponse string                 `protobuf:"bytes,6,opt,name=gemini_response,json=geminiResponse,proto3" json:"gemini_response,omitempty"`
	TopComments    []*Comment             `protobuf:"bytes,7,rep,name=top_comments,json=topComments,proto3" json:"top_comments,omitempty"`
	Status         string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt    string                 `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_proto_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *AnalysisResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AnalysisResult) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *AnalysisResult) GetMetadata() *VideoMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalysisResult) GetSafetyScore() int32 {
	if x != nil {
		return x.SafetyScore
	}
	return 0
}

func (x *AnalysisResult) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *AnalysisResult) GetGeminiResponse() string {
	if x != nil {
		return x.GeminiResponse
	}
	return ""
}

func (x *AnalysisResult) GetTopComments() []*Comment {
	if x != nil {
		return x.TopComments
	}
	return nil
}

func (x *AnalysisResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AnalysisResult) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type VideoMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	ViewCount     int64                  `protobuf:"varint,5,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMetadata) Reset() {
	*x = VideoMetadata{}
	mi := &file_proto_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadata) ProtoMessage() {}

func (x *VideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadata.ProtoReflect.Descriptor instead.
func (*VideoMetadata) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *VideoMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoMetadata) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *VideoMetadata) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoMetadata) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *VideoMetadata) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Likes         int64                  `protobuf:"varint,3,opt,name=likes,proto3" json:"likes,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_proto_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *Comment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Comment) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Comment) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Cancelled     bool                   `protobuf:"varint,2,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_analysis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analysis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_analysis_proto_rawDescGZIP(), []int{10}
}

func (x *CancelResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_analysis_proto protoreflect.FileDescriptor

const file_proto_analysis_proto_rawDesc = "" +
	"\n" +
	"\x14proto/analysis.proto\x12\banalysis\"c\n" +
	"\x0fAnalysisRequest\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x123\n" +
	"\aoptions\x18\x02 \x01(\v2\x19.analysis.AnalysisOptionsR\aoptions\"\x8c\x01\n" +
	"\x0fAnalysisOptions\x12 \n" +
	"\vsensitivity\x18\x01 \x01(\x05R\vsensitivity\x12)\n" +
	"\x10analyze_comments\x18\x02 \x01(\bR\x0fanalyzeComments\x12,\n" +
	"\x12top_comments_count\x18\x03 \x01(\x05R\x10topCommentsCount\"[\n" +
	"\x10AnalysisResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"(\n" +
	"\x0fProgressRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x8e\x01\n" +
	"\rProgressEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x05R\bprogress\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"&\n" +
	"\rResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xf3\x02\n" +
	"\x0eAnalysisResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.analysis.VideoMetadataR\bmetadata\x12!\n" +
	"\fsafety_score\x18\x04 \x01(\x05R\vsafetyScore\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\x12'\n" +
	"\x0fgemini_response\x18\x06 \x01(\tR\x0egeminiResponse\x124\n" +
	"\ftop_comments\x18\a \x03(\v2\x11.analysis.CommentR\vtopComments\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\tR\vcompletedAt\"\xbf\x01\n" +
	"\rVideoMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\x12\x1d\n" +
	"\n" +
	"view_count\x18\x05 \x01(\x03R\tviewCount\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\tR\vpublishedAt\"_\n" +
	"\aComment\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05likes\x18\x03 \x01(\x03R\x05likes\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"&\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"_\n" +
	"\x0eCancelResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\tcancelled\x18\x02 \x01(\bR\tcancelled\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xa6\x02\n" +
	"\x0fAnalysisService\x12F\n" +
	"\rStartAnalysis\x12\x19.analysis.AnalysisRequest\x1a\x1a.analysis.AnalysisResponse\x12F\n" +
	"\x0eStreamProgress\x12\x19.analysis.ProgressRequest\x1a\x17.analysis.ProgressEvent0\x01\x12>\n" +
	"\tGetResult\x12\x17.analysis.ResultRequest\x1a\x18.analysis.AnalysisResult\x12C\n" +
	"\x0eCancelAnalysis\x12\x17.analysis.CancelRequest\x1a\x18.analysis.CancelResponseB3Z1github.com/vanillaturtlechips/silver-guardian/backend/protob\x06proto3"

var (
	file_proto_analysis_proto_rawDescOnce sync.Once
	file_proto_analysis_proto_rawDescData []byte
)

func file_proto_analysis_proto_rawDescGZIP() []byte {
	file_proto_analysis_proto_rawDescOnce.Do(func() {
		file_proto_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)))
	})
	return file_proto_analysis_proto_rawDescData
}

var file_proto_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_analysis_proto_goTypes = []any{
	(*AnalysisRequest)(nil),  // 0: analysis.AnalysisRequest
	(*AnalysisOptions)(nil),  // 1: analysis.AnalysisOptions
	(*AnalysisResponse)(nil), // 2: analysis.AnalysisResponse
	(*ProgressRequest)(nil),  // 3: analysis.ProgressRequest
	(*ProgressEvent)(nil),    // 4: analysis.ProgressEvent
	(*ResultRequest)(nil),    // 5: analysis.ResultRequest
	(*AnalysisResult)(nil),   // 6: analysis.AnalysisResult
	(*VideoMetadata)(nil),    // 7: analysis.VideoMetadata
	(*Comment)(nil),          // 8: analysis.Comment
	(*CancelRequest)(nil),    // 9: analysis.CancelRequest
	(*CancelResponse)(nil),   // 10: analysis.CancelResponse
}
var file_proto_analysis_proto_depIdxs = []int32{
	1,  // 0: analysis.AnalysisRequest.options:type_name -> analysis.AnalysisOptions
	7,  // 1: analysis.AnalysisResult.metadata:type_name -> analysis.VideoMetadata
	8,  // 2: analysis.AnalysisResult.top_comments:type_name -> analysis.Comment
	0,  // 3: analysis.AnalysisService.StartAnalysis:input_type -> analysis.AnalysisRequest
	3,  // 4: analysis.AnalysisService.StreamProgress:input_type -> analysis.ProgressRequest
	5,  // 5: analysis.AnalysisService.GetResult:input_type -> analysis.ResultRequest
	9,  // 6: analysis.AnalysisService.CancelAnalysis:input_type -> analysis.CancelRequest
	2,  // 7: analysis.AnalysisService.StartAnalysis:output_type -> analysis.AnalysisResponse
	4,  // 8: analysis.AnalysisService.StreamProgress:output_type -> analysis.ProgressEvent
	6,  // 9: analysis.AnalysisService.GetResult:output_type -> analysis.AnalysisResult
	10, // 10: analysis.AnalysisService.CancelAnalysis:output_type -> analysis.CancelResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_analysis_proto_init() }
func file_proto_analysis_proto_init() {
	if File_proto_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analysis_proto_rawDesc), len(file_proto_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analysis_proto_goTypes,
		DependencyIndexes: file_proto_analysis_proto_depIdxs,
		MessageInfos:      file_proto_analysis_proto_msgTypes,
	}.Build()
	File_proto_analysis_proto = out.File
	file_proto_analysis_proto_goTypes = nil
	file_proto_analysis_proto_depIdxs = nil
}
